-- Users table
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  clerk_id VARCHAR(255) UNIQUE,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255),
  name VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User profiles (background, skills, goals, time availability)
CREATE TABLE IF NOT EXISTS user_profiles (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  background TEXT,
  current_skills TEXT[],
  learning_goals TEXT,
  time_availability_hours_per_week INTEGER,
  preferred_learning_style VARCHAR(50),
  target_industry VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id)
);

-- Study roadmaps (generated by LLM)
CREATE TABLE IF NOT EXISTS roadmaps (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  roadmap_data JSONB NOT NULL,
  estimated_duration_weeks INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Roadmap topics/modules
CREATE TABLE IF NOT EXISTS roadmap_topics (
  id SERIAL PRIMARY KEY,
  roadmap_id INTEGER REFERENCES roadmaps(id) ON DELETE CASCADE,
  topic_name VARCHAR(255) NOT NULL,
  description TEXT,
  order_index INTEGER NOT NULL,
  estimated_hours INTEGER,
  prerequisites TEXT[],
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Certifications
CREATE TABLE IF NOT EXISTS certifications (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  provider VARCHAR(255),
  description TEXT,
  difficulty_level VARCHAR(50),
  estimated_study_hours INTEGER,
  cost DECIMAL(10, 2),
  validity_period_months INTEGER,
  category VARCHAR(100),
  website_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User certification recommendations
CREATE TABLE IF NOT EXISTS user_certifications (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  certification_id INTEGER REFERENCES certifications(id) ON DELETE CASCADE,
  roadmap_id INTEGER REFERENCES roadmaps(id) ON DELETE SET NULL,
  recommendation_reason TEXT,
  priority INTEGER DEFAULT 0,
  status VARCHAR(50) DEFAULT 'recommended', -- recommended, in_progress, completed, skipped
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- YouTube resources
CREATE TABLE IF NOT EXISTS youtube_resources (
  id SERIAL PRIMARY KEY,
  roadmap_topic_id INTEGER REFERENCES roadmap_topics(id) ON DELETE CASCADE,
  video_id VARCHAR(100),
  playlist_id VARCHAR(100),
  title VARCHAR(500),
  description TEXT,
  channel_name VARCHAR(255),
  duration_seconds INTEGER,
  thumbnail_url VARCHAR(500),
  resource_type VARCHAR(50) DEFAULT 'video', -- video, playlist
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Learning progress tracking
CREATE TABLE IF NOT EXISTS learning_progress (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  roadmap_id INTEGER REFERENCES roadmaps(id) ON DELETE CASCADE,
  roadmap_topic_id INTEGER REFERENCES roadmap_topics(id) ON DELETE CASCADE,
  week_number INTEGER NOT NULL,
  hours_studied DECIMAL(5, 2) DEFAULT 0,
  completion_percentage INTEGER DEFAULT 0,
  notes TEXT,
  completed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, roadmap_topic_id, week_number)
);

-- Weekly progress summaries
CREATE TABLE IF NOT EXISTS weekly_progress (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  roadmap_id INTEGER REFERENCES roadmaps(id) ON DELETE CASCADE,
  week_number INTEGER NOT NULL,
  week_start_date DATE NOT NULL,
  total_hours_studied DECIMAL(5, 2) DEFAULT 0,
  topics_completed INTEGER DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, roadmap_id, week_number)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON user_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_roadmaps_user_id ON roadmaps(user_id);
CREATE INDEX IF NOT EXISTS idx_roadmap_topics_roadmap_id ON roadmap_topics(roadmap_id);
CREATE INDEX IF NOT EXISTS idx_user_certifications_user_id ON user_certifications(user_id);
CREATE INDEX IF NOT EXISTS idx_youtube_resources_topic_id ON youtube_resources(roadmap_topic_id);
CREATE INDEX IF NOT EXISTS idx_learning_progress_user_id ON learning_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_learning_progress_week ON learning_progress(user_id, week_number);
CREATE INDEX IF NOT EXISTS idx_weekly_progress_user_week ON weekly_progress(user_id, roadmap_id, week_number);
